name: flutter_survey_js
repository: https://github.com/Goxiaoy/flutter_survey_js
packages:
  - schema/*
  - schema/*/*
  - .
command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  build:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: build_runner
  analyze:
    exec: flutter analyze --no-fatal-infos
  test:
    exec: flutter test
    select-package:
      dir-exists: test
  outdated:
    exec: dart pub outdated
  upgrade:
    exec: dart pub upgrade --major-versions